name: Despliegue a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install --global surge

      - name: Desplegar a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge ./ --domain mi-sitio-dev.surge.sh --token $SURGE_TOKEN
